"""
Pharma Sales Analytics -- Database Seeder
=========================================
Reads CSV files generated by generate_data.py and loads them
into the PostgreSQL database.

Idempotent: drops and recreates all tables on each run.
"""

import os
import csv
from pathlib import Path

import psycopg2
from dotenv import load_dotenv

# Load environment variables
load_dotenv(Path(__file__).parent.parent / ".env")

DATA_DIR = Path(__file__).parent
SQL_DIR  = Path(__file__).parent.parent / "sql"

DB_CONFIG = {
    "host":     os.getenv("DB_HOST", "localhost"),
    "port":     int(os.getenv("DB_PORT", 5432)),
    "dbname":   os.getenv("DB_NAME", "pharma_analytics"),
    "user":     os.getenv("DB_USER", "admin"),
    "password": os.getenv("DB_PASSWORD", "admin123"),
}


def get_connection():
    """Create a new database connection."""
    return psycopg2.connect(**DB_CONFIG)


def execute_schema(conn):
    """Run schema.sql to create (or recreate) all tables."""
    schema_path = SQL_DIR / "schema.sql"
    with open(schema_path, "r", encoding="utf-8") as f:
        schema_sql = f.read()

    with conn.cursor() as cur:
        cur.execute(schema_sql)
    conn.commit()
    print("  [OK] Schema created (tables dropped and recreated)")


def load_csv(conn, table_name, csv_filename, columns):
    """
    Bulk-load a CSV file into a PostgreSQL table using COPY.
    Falls back to INSERT if COPY is not available.
    """
    csv_path = DATA_DIR / csv_filename

    if not csv_path.exists():
        print(f"  [FAIL] {csv_filename} not found -- run generate_data.py first")
        return 0

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        print(f"  [FAIL] {csv_filename} is empty")
        return 0

    # Use COPY FROM for fast bulk insert
    with conn.cursor() as cur:
        # Build the COPY command
        cols = ", ".join(columns)
        placeholders = ", ".join(["%s"] * len(columns))
        insert_sql = f"INSERT INTO {table_name} ({cols}) VALUES ({placeholders})"

        for row in rows:
            values = [row[col] for col in columns]
            cur.execute(insert_sql, values)

    conn.commit()
    print(f"  [OK] {table_name}: {len(rows)} rows loaded from {csv_filename}")
    return len(rows)


def reset_sequences(conn):
    """Reset serial sequences to match loaded data."""
    # Explicit mapping: (table_name, sequence_name, pk_column)
    seq_info = [
        ("territories", "territories_territory_id_seq", "territory_id"),
        ("reps",        "reps_rep_id_seq",              "rep_id"),
        ("products",    "products_product_id_seq",       "product_id"),
        ("physicians",  "physicians_physician_id_seq",   "physician_id"),
        ("sales",       "sales_sale_id_seq",             "sale_id"),
    ]
    with conn.cursor() as cur:
        for table, seq, pk_col in seq_info:
            cur.execute(
                f"SELECT setval('{seq}', COALESCE((SELECT MAX({pk_col}) FROM {table}), 1))"
            )
    conn.commit()
    print("  [OK] Serial sequences reset")


def main():
    print("=" * 50)
    print("PHARMA SALES ANALYTICS -- DATABASE SEEDER")
    print("=" * 50)
    print(f"\nConnecting to {DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['dbname']}...")

    try:
        conn = get_connection()
        print("  [OK] Connected to PostgreSQL\n")
    except psycopg2.OperationalError as e:
        print(f"\n  [FAIL] Connection failed: {e}")
        print("  -> Make sure Docker is running: docker-compose up -d")
        return

    try:
        # 1. Create schema
        print("Step 1: Creating schema...")
        execute_schema(conn)

        # 2. Load data in dependency order
        print("\nStep 2: Loading data...")
        load_csv(conn, "territories", "territories.csv",
                 ["territory_id", "name", "region", "manager"])

        load_csv(conn, "products", "products.csv",
                 ["product_id", "name", "category", "price_per_unit", "launch_date"])

        load_csv(conn, "reps", "reps.csv",
                 ["rep_id", "name", "territory_id", "hire_date", "target_quota"])

        load_csv(conn, "physicians", "physicians.csv",
                 ["physician_id", "name", "specialty", "territory_id", "tier", "hospital_affiliation"])

        load_csv(conn, "sales", "sales.csv",
                 ["sale_id", "rep_id", "physician_id", "product_id", "quantity", "sale_date", "amount"])

        # 3. Reset sequences
        print("\nStep 3: Resetting sequences...")
        reset_sequences(conn)

        # 4. Verify
        print("\nStep 4: Verification...")
        with conn.cursor() as cur:
            tables = ["territories", "reps", "products", "physicians", "sales"]
            for table in tables:
                cur.execute(f"SELECT COUNT(*) FROM {table}")
                count = cur.fetchone()[0]
                print(f"  [OK] {table}: {count} rows")

        print(f"\n{'='*50}")
        print("DATABASE SEEDED SUCCESSFULLY")
        print(f"{'='*50}")

    except Exception as e:
        conn.rollback()
        print(f"\n  [FAIL] Error: {e}")
        raise
    finally:
        conn.close()


if __name__ == "__main__":
    main()
